/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoanPackage;

/**
 *
 * @author joopd05
 */
public class LoanGUI extends javax.swing.JFrame implements LoanConstants{
    Loan[] loanList = new Loan[30];
    static int count=0;
    static boolean primeRateEdit=true;
    /**
     * Creates new form LoanGUI
     */
    public LoanGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exceptionPane = new javax.swing.JOptionPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        primeRateLbl = new javax.swing.JLabel();
        primeRateTxt = new javax.swing.JTextField();
        loanNumberLbl = new javax.swing.JLabel();
        loanNumberTxt = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        loanAmountLbl = new javax.swing.JLabel();
        loanAmountTxt = new javax.swing.JTextField();
        termLbl = new javax.swing.JLabel();
        termComboBox = new javax.swing.JComboBox<>();
        loanTypeTxt = new javax.swing.JLabel();
        loanTypeComboBox = new javax.swing.JComboBox<>();
        viewLoanLbl = new javax.swing.JLabel();
        viewLoanComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        primeRateLbl.setText("Current Prime Interest Rate");

        primeRateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeRateTxtActionPerformed(evt);
            }
        });
        primeRateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saveButtonStateKeyReleased(evt);
            }
        });

        loanNumberLbl.setText("Loan Number");

        loanNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanNumberTxtActionPerformed(evt);
            }
        });
        loanNumberTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saveButtonStateKeyReleased(evt);
            }
        });

        lastNameLbl.setText("Last Name");

        lastNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saveButtonStateKeyReleased(evt);
            }
        });

        loanAmountLbl.setText("Loan Amount");

        loanAmountTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saveButtonStateKeyReleased(evt);
            }
        });

        termLbl.setText("Term");

        termComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1 Year", "3 Years", "5 Years" }));
        termComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonStateCB(evt);
            }
        });

        loanTypeTxt.setText("Loan Type");

        loanTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Business Loan", "Personal Loan" }));
        loanTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonStateCB(evt);
            }
        });

        viewLoanLbl.setText("What do you want to view?");

        viewLoanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "All Loans", "All Business Loans", "All Personal Loans", "A Particular Loan" }));
        viewLoanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLoanComboBoxActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(loanTypeTxt)
                                            .addComponent(termLbl)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lastNameLbl)
                                            .addComponent(loanNumberLbl)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(loanAmountLbl)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loanNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(loanAmountTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(termComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(loanTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                                        .addComponent(lastNameTxt))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(primeRateLbl)
                                .addGap(31, 31, 31)
                                .addComponent(primeRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(viewLoanLbl)
                                .addGap(18, 18, 18)
                                .addComponent(viewLoanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(saveButton)
                        .addGap(43, 43, 43)
                        .addComponent(clearButton)
                        .addGap(29, 29, 29)
                        .addComponent(exitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primeRateLbl)
                    .addComponent(viewLoanLbl)
                    .addComponent(viewLoanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanNumberLbl)
                            .addComponent(loanNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loanAmountLbl))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(termLbl)
                            .addComponent(termComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanTypeTxt)
                            .addComponent(loanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(clearButton)
                    .addComponent(exitButton))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewLoanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLoanComboBoxActionPerformed
        if(viewLoanComboBox.getSelectedItem().toString()!="Loan Number               Last Name               Loan Amount               Term               Interest rate               Total amount owed"){
            jTextArea1.setText("Loan Number               Last Name               Loan Amount               Term               Interest rate               Total amount owed");
        }
    
        switch(viewLoanComboBox.getSelectedItem().toString()){
            case "All Loans":
                for(int i=0; i<count; i++){
                    jTextArea1.append(loanList[i].toString());
                }
                break;
            case "All Business Loans":
                for(int i=0; i<count; i++){
                    if(loanList[i] instanceof BusinessLoan)
                        jTextArea1.append(loanList[i].toString());
                }
                break;
            case "All Personal Loans":
                for(int i=0; i<count; i++){
                    if(loanList[i] instanceof PersonalLoan)
                        jTextArea1.append(loanList[i].toString());
                }
                break;
            case "A Particular Loan":
                String particularLoanNumber = jOptionPane1.showInputDialog(null, "Enter a loan number");
                for(int i=0; i<count; i++){
                    if(loanList[i].getLoanNumber() == Integer.parseInt(particularLoanNumber))
                        jTextArea1.append(loanList[i].toString());
                }
                break;
                
        }
    }//GEN-LAST:event_viewLoanComboBoxActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int confirmed = exceptionPane.showConfirmDialog(null, "Are you sure you want to exit the program?", "Exit Program Message Box",exceptionPane.YES_NO_OPTION);
        if (confirmed == exceptionPane.YES_OPTION) 
           System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(this.checkExceptions()){
            jTextArea1.setText("");
            if(loanTypeComboBox.getSelectedItem()=="Business Loan"){
                loanList[0+count] = new BusinessLoan(Integer.parseInt(loanNumberTxt.getText()), lastNameTxt.getText(), Double.parseDouble(loanAmountTxt.getText()), termStringToInt(), Double.parseDouble(primeRateTxt.getText()));
            }else if(loanTypeComboBox.getSelectedItem()=="Personal Loan"){
                loanList[0+count] = new PersonalLoan(Integer.parseInt(loanNumberTxt.getText()), lastNameTxt.getText(), Double.parseDouble(loanAmountTxt.getText()), termStringToInt(), Double.parseDouble(primeRateTxt.getText()));
            }
            count++;
            primeRateTxt.setEnabled(false);
            primeRateEdit=false;
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void saveButtonStateCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonStateCB
        if(primeRateTxt.getText().length() == 0 || loanNumberTxt.getText().length() == 0 || lastNameTxt.getText().length() == 0 || loanAmountTxt.getText().length() == 0 || termComboBox.getSelectedItem().toString()=="--Select--" || loanTypeComboBox.getSelectedItem().toString()=="--Select--")
                saveButton.setEnabled(false);
            else    
                saveButton.setEnabled(true);
    }//GEN-LAST:event_saveButtonStateCB

    private void saveButtonStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveButtonStateKeyReleased
        if(primeRateTxt.getText().length() == 0 || loanNumberTxt.getText().length() == 0 || lastNameTxt.getText().length() == 0 || loanAmountTxt.getText().length() == 0 || termComboBox.getSelectedItem().toString()=="--Select--" || loanTypeComboBox.getSelectedItem().toString()=="--Select--")
                saveButton.setEnabled(false);
            else    
                saveButton.setEnabled(true);
    }//GEN-LAST:event_saveButtonStateKeyReleased

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        if(primeRateEdit)
            primeRateTxt.setText("");
        
        loanNumberTxt.setText("");
        lastNameTxt.setText("");
        loanAmountTxt.setText("");
        termComboBox.setSelectedIndex(0);
        loanTypeComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void primeRateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeRateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeRateTxtActionPerformed

    private void loanNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanNumberTxtActionPerformed
    
    
    public int termStringToInt(){
        switch (termComboBox.getSelectedItem().toString()){
            case "1 Year":
                return 1;
            case "3 Years":
                return 3;
            case "5 Years":
                return 5;     
        }
        return 0;
    }
    
    public boolean checkExceptions(){
        
        try{
            Integer.parseInt(loanNumberTxt.getText());
            Double.parseDouble(loanAmountTxt.getText()); 
            Double.parseDouble(primeRateTxt.getText());
        }catch(NumberFormatException ic){
                exceptionPane.showMessageDialog(null, "Please enter valid input/s", "Alert", exceptionPane.WARNING_MESSAGE);
                return false;
        }
        
        for(int i=0; i<count; i++){
            if(Integer.parseInt(loanNumberTxt.getText())==loanList[i].getLoanNumber()){
                exceptionPane.showMessageDialog(null, "Loan Number Already Exists!", "Alert", exceptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        

        if(Double.parseDouble(loanAmountTxt.getText())==0 || Double.parseDouble(loanAmountTxt.getText())>MAX_LOAN_AMOUNT){
            exceptionPane.showMessageDialog(null, "Please enter a valid loan amount", "Alert", exceptionPane.WARNING_MESSAGE);
            return false;
        }
        
        
        return true;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JOptionPane exceptionPane;
    private javax.swing.JButton exitButton;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JLabel loanAmountLbl;
    private javax.swing.JTextField loanAmountTxt;
    private javax.swing.JLabel loanNumberLbl;
    private javax.swing.JTextField loanNumberTxt;
    private javax.swing.JComboBox<String> loanTypeComboBox;
    private javax.swing.JLabel loanTypeTxt;
    private javax.swing.JLabel primeRateLbl;
    private javax.swing.JTextField primeRateTxt;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> termComboBox;
    private javax.swing.JLabel termLbl;
    private javax.swing.JComboBox<String> viewLoanComboBox;
    private javax.swing.JLabel viewLoanLbl;
    // End of variables declaration//GEN-END:variables
}
